eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://CLIENT
          predicates:
            - Path=/v1/client/**,/v1/clientDocumentType/**,/v1/clientType/**
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/v1/product/**,/v1/productType/**,/v1/productSubType/**
        - id: pasivoahorro
          uri: lb://PASIVOAHORRO
          predicates:
            - Path=/v1/pasivoahorro/transaction/**,/v1/pasivoahorro/transactionType/**,/v1/pasivoahorro/**,/v1/pasivoahorro/getByDocumentNumber/**,/v1/pasivoahorro/getByAccountNumber/**,
        - id: pasivocuentacorriente
          uri: lb://PASIVOCUENTACORRIENTE
          predicates:
            - Path=/v1/pasivocuentacorriente/transaction/**,/v1/pasivocuentacorriente/transactionType/**,/v1/pasivocuentacorriente/**,/v1/pasivocuentacorriente/getByDocumentNumber/**,/v1/pasivocuentacorriente/getByAccountNumber/**,

        - id: activopersonal
          uri: lb://ACTIVOPERSONAL
          predicates:
            - Path=/v1/activopersonal/**,/v1/activopersonal/transaction/**,/v1/activopersonal/transactionType/**

        - id: activoempresarial
          uri: lb://ACTIVOEMPRESARIAL
          predicates:
            - Path=/v1/activoempresarial/**,/v1/activoempresarial/transaction/**,/v1/activoempresarial/transactionType/**

        - id: tarjetacredito
          uri: lb://TARJETACREDITO
          predicates:
            - Path=/v1/tarjetacredito/**,/v1/tarjetacredito/transaction/**,/v1/tarjetacredito/transactionType/**
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false